### ISSUE TITLE
Error 'Проверка окружения и начало выполнения задания'

### ISSUE THREAD

**Issue by IlyaMKuroptev** [GPGPUCourse2018/Task0EnumDevices#7]
- OS, процессор и видеокарта
Ubuntu 18.04.1 LTS через VirtualBox, 2.8 GHz Intel Core i7, Intel Iris.

- Успешно ли прошла установка Intel-CPU драйвера
Успешно.

- Вывод ./enumDevices
terminate called after throwing an instance of 'std::runtime_error'
    what(): Can't init OpenCL driver!
Aborted (Core dumped)

**Comment by PolarNick239** [comment]
1) Напишите вывод этих команд:
 - ```locate libOpenCL.so```
 - ```locate libOpenCL.so.1```

2) Intel-CPU драйвер установился в папку вроде этой - ```/opt/intel/opencl-1.2-5.2.0.10002```, проверьте что у вас она есть (и что в ```/opt/intel/opencl-1.2-5.2.0.10002/lib64/``` есть файл ```libOpenCL.so```), и попробуйте запустить задание следующим образом:
```LD_LIBRARY_PATH=/opt/intel/opencl-1.2-5.2.0.10002/lib64/ ./enumDevices```

**Comment by sbogolepov** [comment]
Ни VirtualBox, ни Parallels не поддерживают OpenCL, судя по всему.

**Comment by PolarNick239** [comment]
В VirtualBox Intel-CPU драйвер работает :)
Просто что-то не так сконфигурировалось в ОС, виртуализация не должна влиять.

**Comment by PolarNick239** [comment]
Правильное решение:
```sudo apt install ocl-icd-libopencl1```
После этого ./enumDevices должен работать. Помогло?

**Comment by IlyaMKuroptev** [comment]
> Правильное решение:
> `sudo apt install ocl-icd-libopencl1`
> После этого ./enumDevices должен работать. Помогло?

Помогло, но я решил перенести на OsX, там работает без проблем.
